server:
  port: 81

spring:
  application:
    name: cloud-consumerconsul-order81

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}