server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT
    username: root
    password: _wky123
    driver-class-name: com.mysql.cj.jdbc.Driver
#微服务名称
  application:
    name: cloud-provider-payment


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wky.springcloud.entities
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8002
    prefer-ip-address: true